server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server0:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: eureka-server1